apiVersion: v1
kind: Service
metadata:
  name: test-coworking-analytics
spec:
  type: LoadBalancer
  selector:
    service: test-coworking-analytics
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-coworking-analytics
  labels:
    name: test-coworking-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      service: test-coworking-analytics
  template:
    metadata:
      labels:
        service: test-coworking-analytics
    spec:
      containers:
      - name: test-coworking-analytics
        image: 926743903823.dkr.ecr.us-east-1.amazonaws.com/test-coworking-analytics:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        envFrom:
        - configMapRef:
            name: postgresql-service
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: postgres-password
      restartPolicy: Always